apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "niccobot.fullname" . }}
  labels:
    {{- include "niccobot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "niccobot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "niccobot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: DOTENV
              value: "/niccobot/.env"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: sqlite-storage
              mountPath: "/niccobot/database.sqlite"  # Container path where the volume is mounted
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.name }}
      imagePullSecrets:
      - name: regcred