replicaCount: 1

image:
  repository: crowlc/niccobot
  pullPolicy: IfNotPresent
  tag: "1.0.1"
  pullSecret: dockerhub-secret

service:
  type: ClusterIP
  port: 8080

env:
  - name: DOTENV
    value: "/niccobot/.env"
  - name: SQL_DB
    value: "sqlite:///niccobot/database.sqlite"


#persistentVolume:
#  name: sqlite-pv
#  storageClassName: local-path
#  capacity: 3Gi
#  accessMode: ReadWriteOnce

persistentVolumeClaim:
  name: sqlite-pvc
  accessMode: "ReadWriteOnce"
  capacity: "3Gi"
  storageClassName: "local-path"

resources:
